# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dashibodi
email: paul@dashibodi.com
description: >- # this means to ignore newlines until "baseurl:"
  Dashibodi is a project aimed at developing and maintaining a dashboard for Kenya.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dashibodi.com" # the base hostname & protocol for your site, e.g. http://example.com
project_twitter_username: Dashibodi
github_username: PMWan
owner: Paul Wandimi

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate-v2

sass:
  style: compressed

collections:
  charts:
    output: true
    permalink: :slug

pagination: 
  enabled: true
  collection: charts
  per_page: 12
  sort_reverse: true
  title: ":title"
  permalink: '/page/:num/'

# Changed _data to data so that it's included in _site when site generation occurs.
# Did this so that chartist.js library can have access to data when generating charts
data_dir: 'data'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile